### PR TITLE
footer

### LINKED ISSUE #8: Create footer

### PR DESCRIPTION
**Pull request by AdamPrisen**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type
- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Chore

### What's new?

- [x] PR closes #8 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR
- [ ] I've written some unit tests 🧪

### Optional

- [ ] I found edge cases

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### CODE REVIEW

**Comment by vikiival** [comment]
Few things: 

- I would get for smaller footer. (height)

Screenshot 2022-11-29 at 09 39 40

Remove contact column
Screenshot 2022-11-29 at 12 03 52

Remove TOC column
Screenshot 2022-11-29 at 12 03 58

- Let's have normal links - rename column to About
ParaSpell GitHub - https://github.com/paraspell
KodaDot GitHub - https://github.com/kodadot

- Socials

- maybe use some from the kodadot (discord, twitter, reddit)

Screenshot 2022-11-29 at 12 06 39

- make them much smaller - size of kodadot is enough

**Comment by vikiival** [comment]
Maybe use this logo?

sub-scaffold

**Comment by AdamPrisen** [comment]
@vikiival to the icons from kodadot, when I was looking at the project, I found out that we use icons from @vicons package so I tried to stick to icons from this package. But if its necessary, I can switch to icons from kodadot but I need to know are those icons from some library or should I only export them from kodadot as svg ?

**Comment by AdamPrisen** [comment]
@vikiival suggestions  applied :blush:

**Pull request merged**
